### ISSUE TITLE
support "next / previous goal"

### ISSUE THREAD

**Issue by yuzuco15** [yuzumikan15/ocaml-alab-mode#13]

**Comment by kenichi-asai** [comment]
これ、サポートしませんか。実際にプログラミングをしながら hole のデバッグをしているのですが、これがないと恐ろしくプログラミング効率が悪いです。単に next では `(exit(\\*{` を後方に向かって、previous では `}\\*)[0-9]+)` を前方に向かって `re-search-forward/backward` すれば良いだけと思います。

**Comment by yuzuco15** [comment]
agda2-mode にあるものをほとんどそのままでできました．デバッグありがとうございました．
push したのでこのまま close します．
