### ISSUE TITLE
support matching pairs and records

### ISSUE THREAD

**Issue by yuzuco15** [yuzumikan15/ocaml-alab-mode#15]

**Comment by yuzuco15** [comment]
(Dec 21)
done.

**Comment by kenichi-asai** [comment]
- Matching on `int * int` works, but matching on `(int * int) * int` does not work.
- Record fields should be separated by `;`, not `,`.

**Comment by yuzuco15** [comment]
- Detected why this does not work. It will take a bit long time to fix.
- Fixed it.

**Comment by yuzuco15** [comment]
- I fixed the bug matching `(int * int) * int`, but another issue occurred according to this.

``` ocaml
let f: int -> (int * int) * int = fun i -> {}0
```

will be

``` ocaml
let f: int -> (int * int) * int = fun i -> match i with
   (var0, var1) -> {}0
```

Moreover, if you `C-c m` `var0` in the hole 0, it becomes

``` ocaml
let f: int -> (int * int) * int = fun i -> match i with
   (var0, var1) -> match var0 with
        (var0, var1) -> {}0 
```

So, the names of variables need to be fixed...

**Comment by yuzuco15** [comment]
上の `f` のプログラム，最初から `((var0, var1), var2) -> {}0` に match するのがよいでしょうか？
(とすると，tuple だけではなくて展開できるものは最初から全部展開するのがよいでしょうか？)

e.g.

``` ocaml
type person = {name: string; age: int; email: string}

let g: (person, person) -> (name, name) = fun p -> {}0
```

は

``` ocaml
let g: (person, person) -> (name, name) = fun p -> match p with
    ({name = n; age = a; email = e}, {name = n2; age = a2; email = e2}) -> {}0
```

や，`tree_t` の場合なども同じく，一度の match で全部分解した方がよいでしょうか？

(print するときに使っているデータ構造を変更したのでできなくはないですが，改行が入らないのでどこまでやるべきか悩んでいます)

**Comment by kenichi-asai** [comment]
いや、展開するのは最も外側のひとつだけで良いと思います。

名前のクラッシュは別途、考えなくてはいけないと思います。var0 等は毎回「必ず」別の名前に付け替えるように指導するのでしょうが、デフォルトでまあまあの名前をどう提供するかというのは面白い問題のように思います。また、現在のホールから見て、すでに使われている名前を調べて、それに重ならないようにすると言うのも考えられます。

多段のパターンについては、パターンの中の変数について場合分けをしたときには、新たに match 文を入れるのではなく、そのパターンを変更する形にしたいところです。

**Comment by yuzuco15** [comment]
- 名前の問題は実は issue #11 にあがっているので今いただいたコメントをそのままそちらへ引用しました．
- パターンの中の変数についての場合分け，新しい issue としてあげました．

**Comment by yuzuco15** [comment]
別の issue に切り出したのでこちらは close します．
