### ISSUE TITLE
The representation of holes needs parenthesis.

### ISSUE THREAD

**Issue by kenichi-asai** [yuzumikan15/ocaml-alab-mode#16]
The representation of hole should be `(exit(*{}*)n)` rather than `exit(*{}*)n`.  Otherwise, holes cannot appear as an argument of a function.  For example, `List.rev { }0` is interpreted as passing `exit` and `0` to `List.rev`.

**Comment by yuzuco15** [comment]
(Dec 21)
done.
I fixed the related areas of hole.el.

**Comment by kenichi-asai** [comment]
Confirmed.
