### ISSUE TITLE
support matching Optionals

### ISSUE THREAD

**Issue by yuzuco15** [yuzumikan15/ocaml-alab-mode#17]

**Comment by yuzuco15** [comment]
> - C-c m を任意の式に対して行う件、hole に書かれた式が e だったとき、 
>   OCaml に渡す際にそれを let a = e in hole にして、a の型を調べれば実 
>   現できそう。 
> - ただし、これをしようとする際、OCaml の warning を全て off にしておか 
>   ないと、変数 a が使われていないという warning が出て、うまくいかな 
>   いっぽい。

**Comment by yuzuco15** [comment]
(Dec 21)
done.

## コメントについて
- C-c m する際，対象となっている hole の型 `t` は既に分かっていて，それがユーザが定義した型であれば structure 内にあるはずなのでそこから各コンストラクタ名，フィールド名を取ってきています．
- 問題は list や option など OCaml に最初から入っている型で，これは `t` の中に `"list"`，`"option"` という string が入っているのを探し，これらを特別扱いして出力しています．(コンストラクタ名が既に分かっているため)

**Comment by kenichi-asai** [comment]
- 第１点目、「対象となっている hole の型 `t`」ではなく「hole に書かれている変数の型 `t`」ですね。それが option 型だった場合、うまくいくのは確認しました。（ただ、その際、挿入される match 文の最後に、ひとつ改行が余計と思います。）
- 一方、hole に書ける式は、以前と同じく変数のみのままです。例えば、

```
let f : (int -> int option) -> int = fun g ->
  {g 3}0
```

で C-c m はできないです。これを、

```
let f : (int -> int option) -> int = fun g ->
  match g 3 with
  | None -> { }0
  | Some (v) -> { }1
```

に展開したいです。で、これは元の式をまず

```
let f : (int -> int option) -> int = fun g ->
  let a = g 3 in {a }0
```

に置き換えた上で型推論にかけ、`a` の型を調べ、let 文を消去した上で、その型に応じた match 文を入れれば簡単に実現できそうです、というのが元のコメントの趣旨です。

**Comment by yuzuco15** [comment]
コメントありがとうございます．趣旨を理解しました．やってみます．
(余計な改行が入るのは OCaml 側 - expander.ml 側で Format.fprintf を使っているからだと思います．これの改行が入らないものを探しています)

**Comment by kenichi-asai** [comment]
Format.fprintf に渡す "%d" とかの最後に "\n" が入っているのを消せば良いという問題ではない？

**Comment by kenichi-asai** [comment]
Format.fprintf では、"@." は「改行＋ flush」のようです。改行せずに flush のみする場合は "@?" だそうです。

**Comment by yuzuco15** [comment]
任意の式で match をかけるように，`let a = expression in {a}0` としてやってみました．いかがでしょうか．

**Comment by yuzuco15** [comment]
"@." ではなく "@?" にしました．いかがでしょうか．

**Comment by kenichi-asai** [comment]
1. 改行は、うまく行っている感じです。
2. `C-c m` の場合、hole が空だったらエラー処理（「hole に式が必要です」と表示するとか）したいです。（今は、let 文を入れた後で Syntax error (?) が出ています。）
3. `type ltable = (string * string list) list` という定義のもとで、`ltable` 型を持つ変数について `C-c m` しようとすると、空の match 文が出て来てしまいます。
4. `C-c m` も含めて、コンパイラの型推論を呼び出すときには、その前に syntax error がないかをあらかじめチェックしたいです。（で、コンパイラに通らない場合は、まずはそっちを先にユーザに直してもらう。）
5. 任意の式の match 文を出すのは、うまく行っているように見えます。

**Comment by yuzuco15** [comment]
1.  エラー処理，対応します．
2. `ltable` 型の match，Typedtree.structure での型情報が `Ttype_abstract` で何も情報がないのでもうちょっと深いところ (Types.type_declaration?) までいかないといけないみたいです…現在対応中です．
3. syntax error がないか先にコンパイラにかけるのを別の issue として立てます．

**Comment by yuzuco15** [comment]
in Parsetree.mli,

``` ocaml
(*
  type t                     (abstract, no manifest)
  type t = T0                (abstract, manifest=T0)
  type t = C of T | ...      (variant,  no manifest)
  type t = T0 = C of T | ... (variant,  manifest=T0)
  type t = {l: T; ...}       (record,   no manifest)
  type t = T0 = {l : T; ...} (record,   manifest=T0)
  type t = ..                (open,     no manifest)
*)
```

**Comment by yuzuco15** [comment]
manifest の中身をまた `print_match_expr` すればよい

**Comment by yuzuco15** [comment]
`Ttype_abstract` になっているものの `match` をサポートしました．
`issue.ml` にいろいろな例があるので試してみてください．

**Comment by yuzuco15** [comment]
よさそうなので close します
