### ISSUE TITLE
type-check when refine with an argument

### ISSUE THREAD

**Issue by yuzuco15** [yuzumikan15/ocaml-alab-mode#9]
- need to pass the program with the argument that user inputs (i.e. remove the hole under the argument) to the compiler in order to type-check.

**Comment by yuzuco15** [comment]
(Dec 21)
done.
- refine the hole only when the compiler did not print any error.
- otherwise, delete the expression and insert a hole.

**Comment by kenichi-asai** [comment]
Confirmed.  However, after `C-c ,`, the cursor goes to the beginning of the buffer.  The cursor should stay at the hole.

**Comment by yuzuco15** [comment]
I will fix the cursor position as soon as  possible.
